[package]
name    = "ggs-strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
ggs-core = { path = "../ggs-core" }
rand     = { workspace = true }
rayon    = { workspace = true }
serde    = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name    = "simulation"
harness = false
